### ISSUE TITLE
Logprobs are not exposed in chat completions

### ISSUE THREAD

**Issue by borowis** [sashirestela/simple-openai#106]
### Feature Description

Logprobs are partially exposed in Chat completions but it's not really possible to get them back : / They seem to be present in deprecated completions API, please see Open AI API documentation https://platform.openai.com/docs/api-reference/chat

### Problem it Solves

I don't see any current workaround, Logprobs solve a lot of problems, see for example https://cookbook.openai.com/examples/using_logprobs

### Proposed Solution

We just need to expose `logprobs` in `io.github.sashirestela.openai.domain.chat`, similar to how it was done in `io.github.sashirestela.openai.domain.completion.Choice`

### See also

I've taken a look at a bunch of clients and so far it seems like only `jvm-openai` supports logprobs :man_shrugging: 
similar issue I've created earlier today https://github.com/aallam/openai-kotlin/issues/326

**Comment by sashirestela** [comment]
@borowis Very thanks to discover this missing field issue. I've just fixed and generated a new simple-openai version 2.3.1 which will be available on Maven repos later today.

I'm curious if you are doing a kind of comparison between OpenAI Java libraries?

**Comment by borowis** [comment]
oh wow, thanks @sashirestela! that was really quick :heart: 

> I'm curious if you are doing a kind of comparison between OpenAI Java libraries?

not of my own will :sweat_smile: it's just the library we picked was missing the `logprobs` and that's how I discovered `simple-openai` client!

**Comment by sashirestela** [comment]
@borowis It's a pleasure to help the community!

Any question/concern/suggestion will be very welcome to improve simple-openai.

Thanks for using simple-openai and if you think this project is valuable to you, there are a few ways to show us your love:

- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.
