### ISSUE TITLE
Assistant demo method commented out, but works fine

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#115]
The [demo::demoRunThreadAndWaitUntilComplete](https://github.com/sashirestela/simple-openai/blob/99f9dff840dd220db89122c00b567e10295e0a20/src/demo/java/io/github/sashirestela/openai/demo/AssistantServiceDemo.java#L223) call is commented out.

I uncommented it locally and it succeeds.

It was commented out here: https://github.com/sashirestela/simple-openai/pull/71

It can be uncommented now.

**Comment by sashirestela** [comment]
Take a look at this comment:

https://github.com/sashirestela/simple-openai/issues/97#issuecomment-2091379198

**Comment by the-gigi** [comment]
Since assistants V1 will be removed in 3.0.0. This issue is irrelevant.
