### ISSUE TITLE
Support for attachments in assistants

### ISSUE THREAD

**Issue by GriesserP** [sashirestela/simple-openai#121]
Thank you very much for your very easy to use library.

I am trying to use an openAi assistants to read documents and having the response streamed. For that I can use this curl command:
```
  curl https://api.openai.com/v1/threads/runs \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -H "OpenAI-Beta: assistants=v2" \
  -d '{
    "assistant_id": "asst_xyz",
    "thread": {
      "messages": [
        {"role": "user", "content": "what are the documents about", "attachments":
         [{"file_id":"file-1", "tools":[{"type":"file_search"}]},
            {"file_id":"file-2", "tools":[{"type":"file_search"}]}]
         }
      ]
    },
    "stream": true
  }'
  ```
  
Now when using the library with:
```
SimpleOpenAI simpleOpenAI = SimpleOpenAI.builder()
        .apiKey("$OPENAI_API_KEY")
        .build();
    Thread thread = simpleOpenAI.threads().create().join();
    String threadId = thread.getId();
    var request = ThreadRunRequest.builder().assistantId("asst_xyz")
        .additionalMessages(
            List.of(
                ThreadMessageRequest.builder()
                    .content("what are the documents about")
                    .role(ThreadMessageRequest.Role.USER)
                    .fileIds(List.of("file-1", "file-2"))
                    .build()
            ))
        .tool(AssistantTool.RETRIEVAL)
        .build();
    var run = simpleOpenAI.threads().createRun(threadId, request).join();
```

I don't get the same result (c.f. screenshots). It seems that the files are not properly attached to the message using the "attachments" property  of the payload. Am I missing something? Thank you in advance for your help!

<img width="1043" alt="Screenshot 2024-05-07 at 08 18 24" src="https://github.com/sashirestela/simple-openai/assets/36691390/2d8b2a41-efbb-4891-a8f7-38856511b31e">

<img width="1043" alt="Screenshot 2024-05-07 at 08 21 50" src="https://github.com/sashirestela/simple-openai/assets/36691390/76b88477-e21a-44c0-b4e9-b4d7d74b1b8a">

**Comment by sashirestela** [comment]
@GriesserP If you don't have any other comment, this issue could be closed.

**Comment by GriesserP** [comment]
Thank you very much for the quick answer.
Il will try with the new version of the library, and will re open the issue if I still have a problem with it
