### ISSUE TITLE
Support for image inputs to the Assistants API

### ISSUE THREAD

**Issue by sashirestela** [sashirestela/simple-openai#126]
Take a look at: https://platform.openai.com/docs/changelog/added-vision-to-assistants

**Comment by Prikis** [comment]
Is there any demo for image upload with the Assistants API?

**Comment by sashirestela** [comment]
https://github.com/sashirestela/simple-openai/blob/main/src/demo/java/io/github/sashirestela/openai/demo/ThreadMessageV2Demo.java#L75

**Comment by sashirestela** [comment]
@Prikis If you find this project valuable there are a few ways you can show us your love, preferably all of them 🙂:
- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.
