### ISSUE TITLE
Conversation2Demo gives a file path error on Windows

### ISSUE THREAD

**Issue by akulyakhtin** [sashirestela/simple-openai#133]
Run Conversation2Demo on windows (I've cloned the repo into G:\Code)

Observe the error:

> Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /G:/Code/simple-openai/src/demo/resources/mistral-ai.txt

The error happens in CleverClient in HttpMultipart.java on line 52:

> Path path = Path.of((new URL((String)entry.getValue())).getPath());

Best regards,
Alex

**Comment by the-gigi** [comment]
The path is `/G:/Code/simple-openai/src/demo/resources/mistral-ai.txt` is invalid on Windows. There should be no slash before the drive letter. Try just `G:/Code/simple-openai/src/demo/resources/mistral-ai.txt`

**Comment by sashirestela** [comment]
@akulyakhtin Thanks for using simple-openai and for detecting this platform issue. I need some time to setup a Windows environment and replicate the issue. I'll let you know more news.

**Comment by akulyakhtin** [comment]
@the-gigi I'm not modifying Conversation2Demo.java in any way. This error happens when I'm executing the latest Conversation2Demo.main as is on Windows.

**Comment by akulyakhtin** [comment]
Hi @sashirestela @the-gigi coukld you, please, review a fix for this issue? The fix is in cleverclient project
https://github.com/sashirestela/cleverclient/pull/72

Thank you very much
Alex

**Comment by sashirestela** [comment]
@akulyakhtin Thanks for proactively help me with this Windows issue.

I'm deploying the new version 1.4.3 of cleverclient and it will be integrated with simple-openai in its next release.

---

If you find this project valuable there are a few ways you can show us your love, preferably all of them 🙂:

- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.

**Comment by akulyakhtin** [comment]
Hi @sashirestela you are welcome.
