### ISSUE TITLE
Do you implement a way of tokenizing text?

### ISSUE THREAD

**Issue by monkiki** [sashirestela/simple-openai#158]
I know the tiktoken Python library, but and even have found Java implementations like jtokkit. Do you include a tokenizer o plan to add one?

Thanks in advance.

**Comment by sashirestela** [comment]
Hi @monkiki , thanks for using simple-openai. No, I don't and no plan to add any. I think that [Jtokkit](https://github.com/knuddelsgmbh/jtokkit) is a great option.

**Comment by monkiki** [comment]
Ok, thanks for the info!
