### ISSUE TITLE
setting number of Epochs in finetuning fails

### ISSUE THREAD

**Issue by jzu-guru** [sashirestela/simple-openai#193]
I've tried to make a finetuning with more than one epoch. Therefore I've added the hyperparameters as following:

`            FineTuningRequest fineTuningRequest = FineTuningRequest.builder()`
`                    .trainingFile(fileId)`
`                    .model("gpt-4o-mini-2024-07-18")`
`                    .suffix("mytest-mk3")`
`                    .hyperparameters(HyperParams.builder().nEpochs(2).build())`
`                    .build();`

But I'm getting an error from openAI:

`Create finetuning...2024-09-24 16:22:19.551+0200 [ForkJoinPool.commonPool-worker-1] ERROR` `io.github.sashirestela.cleverclient.sender.HttpSender - Response : {`
`  "error": {`
`    "message": "invalid nepochs: 2, extra inputs are not permitted",`
`    "type": "invalid_request_error",`
`    "param": "nepochs",`
`    "code": null`
`  }`
`}`

It seems the Parameter is named wrong, because in the openAI API doc it is name "n_epochs" and not "nepochs"

**Comment by sashirestela** [comment]
@jzu-guru Thanks for using simple-openai and for catching this issue. Doing a quick research, I realized that this is a known [tricky behavior](https://github.com/FasterXML/jackson-databind/issues/3366) of the Java Jackson library.

I'm going to provide a fix.

**Comment by sashirestela** [comment]
@jzu-guru The fix is available in the latest release 3.8.2

If you find this project valuable there are a few ways you can show us your love, preferably all of them 🙂:
- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.

**Comment by jzu-guru** [comment]
Thank you for the quick fix.
