### ISSUE TITLE
HTTP Threads Accumulation and Thread-Safety Inquiry with Local LLM Integration

### ISSUE THREAD

**Issue by danielsawan** [sashirestela/simple-openai#204]
Hello,

First of all, thank you for your work on this library. I am using it to integrate a local LLM and I have encountered some strange behavior.

I would like to know if it is necessary to manually close the HTTP request once we receive a response from our LLM. From my stack trace, I see a continuous creation of HTTP threads, which seems to indicate that connections are not being properly closed.

Additionally, is the API thread-safe? I want to ensure that using it in a multi-threaded context will not cause any issues.

Here is the code snippet I am currently using:

```java
HttpClient httpClient = HttpClient.newBuilder()
    .version(HttpClient.Version.HTTP_1_1)
    .followRedirects(HttpClient.Redirect.NORMAL)
    .connectTimeout(Duration.ofSeconds(20))
    .build();

openAI = SimpleOpenAI.builder()
    .baseUrl("http://xxx.xxx.xxx.xxx:1234") // lmstudio
    .apiKey("sk-***")
    .httpClient(httpClient)
    .build();

ChatRequest chatRequest = ChatRequest.builder()
    .model(model)
    .messages(messages)
    .maxTokens(512)
    .build();

CompletableFuture<Chat> futureChat = openAI.chatCompletions().create(chatRequest);
Chat chatResponse = futureChat.join();					
return chatResponse.firstContent();

**Comment by sashirestela** [comment]
Hi @danielsawan thanks for using simple-openai.

> is the API thread-safe? I want to ensure that using it in a multi-threaded context will not cause any issues.

**Answer**: What I can tell you is that the API provides object immutability, so multiple threads can safely access the object concurrently.

> I would like to know if it is necessary to manually close the HTTP request once we receive a response from our LLM.

**Answer**: No, it is not necessary. What you could do is to provide your own executor with your own thread creation strategy. For this, you could use the [executor()](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Builder.html#executor(java.util.concurrent.Executor)) property for the HttpClient.Builder to create an HttpClient which you will pass to the SimpleOpenAI builder.
