### ISSUE TITLE
Version 3.9.1 released to the wrong repository?

### ISSUE THREAD

**Issue by thomasdewaelheyns** [sashirestela/simple-openai#215]
While attempting to upgrade to version 3.9.1 for the "incomplete" fix, I noticed that that version was released on a different repository than Maven Central like the other versions.

According to https://mvnrepository.com/artifact/io.github.sashirestela/simple-openai/3.9.1 it is located on a repo called Velocity (https://mvnrepository.com/repos/velocitypowered-maven-public).

![image](https://github.com/user-attachments/assets/3e7a4654-5411-4236-ba13-5b738ed39b1a)

**Comment by sashirestela** [comment]
@thomasdewaelheyns The artifact was deployed as usual. I don't have any chance to select any specific repository. I'm seeing that the artifact 3.9.1 is on Maven Central.
