### ISSUE TITLE
Server compile error, need Java 8

### ISSUE THREAD

**Issue by SitaMelark** [sashirestela/simple-openai#234]
I'm currently trying to deploy my Spring Boot app on a Java 8 server, but it seems it's not possible due to the simple-openai library, which requires Java 11.

Is there an older version of simple-openai that supports Java 8, or is there a way to make it work?

I’m also investigating how to install Java 11 without setting it as the default and use it only for my project. I cannot upgrade the server's default JDK to 11 because there are many projects that might encounter issues or stop working if I upgrade.

**Comment by sashirestela** [comment]
Hi @SitaMelark thanks for your question.

> Is there an older version of simple-openai that supports Java 8, or is there a way to make it work?

No, there is not. Currently, you need Java 11+ to make it work.

**Comment by sashirestela** [comment]
> I’m also investigating how to install Java 11 without setting it as the default and use it only for my project. I cannot upgrade the server's default JDK to 11 because there are many projects that might encounter issues or stop working if I upgrade.

For that point, I recommend you to use [sdk](https://sdkman.io/usage) to install and work with multiple Java versions.
