### ISSUE TITLE
Unable to extend simple-openai to support additional providers from the outside 

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#247]
I'm looking to add Gemini support to simple-openai (see https://github.com/sashirestela/simple-openai/discussions/221)

I created a **SimpleOpenAIGemini** class similar to [SimpleOpenAIAnyscale](the https://github.com/sashirestela/simple-openai/blob/main/src/main/java/io/github/sashirestela/openai/SimpleOpenAIAnyscale.java) and [SimpleOpenAIAzure](https://github.com/sashirestela/simple-openai/blob/main/src/main/java/io/github/sashirestela/openai/SimpleOpenAIAzure.java).

However, it needs to extend BaseSimpleOpenAI and call its constructor as super(). While BaseSimpleOpenAI itself is public, its constructor is package-private:
https://github.com/sashirestela/simple-openai/blob/065bf67454fb758f27db615a3a250d139ec3e10e/src/main/java/io/github/sashirestela/openai/BaseSimpleOpenAI.java#L50

This means that classes from other packages and in particularly external code can't extend BaseSimpleOpenAI.

![image](https://github.com/user-attachments/assets/45266374-d29e-454a-a6e4-d8e9d076bb87)

Making the constructor public will allow external developers to extend simple-openai with additional providers that can be brought in later like Azure OpenAI and Anyscale if considered useful or remain as external extensions.

**Comment by the-gigi** [comment]
I just noticed the [Improved approach to handle multiple OpenAI providers](https://github.com/sashirestela/simple-openai/pull/246) PR

This issue maybe obsolete if the new approach allows creating new providers externally.

**Comment by sashirestela** [comment]
This has been addressed in the PR #246
