### ISSUE TITLE
Error Handling for Local Image Upload: 'Invalid Image' Issue with OpenAI GPT-4 Vision API

### ISSUE THREAD

**Issue by safouat** [sashirestela/simple-openai#36]
While attempting to upload a local image for processing, I encountered the following error:
**ERROR io.github.sashirestela.cleverclient.sender.HttpSender - Response : {
  "error": {
    "message": "Invalid image.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}**
i tried to pass the Base64-encoded image data to **ContentPartImage** but the error persists 
` public static void main(String[] args) {
        var openai = SimpleOpenAI.builder()
                .apiKey("**")
                .build();

        ImageUrl imageBase64 = loadImageAsBase64("/home/safouat/Desktop/ok12/Openai/src/main/webapp/WEB-INF/13.jpg");
        var chatRequest = ChatRequest.builder()
                .model("gpt-4-vision-preview")
                .messages(List.of(
                        new ChatMsgUser(List.of(
                                new ContentPartText("What do you see in the image? Give in details in no more than 100 words."),
                                new ContentPartImage(imageBase64)
                        ))
                ))
                .temperature(0.0)
                .maxTokens(500)
                .build();

        var chatResponse = openai.chatCompletions().createStream(chatRequest).join();
        chatResponse.filter(chatResp -> chatResp.firstContent() != null)
                .map(chatResp -> chatResp.firstContent())
                .forEach(System.out::print);
        System.out.println();
    }

    private static ImageUrl loadImageAsBase64(String imagePath) {
        try {
            Path path = Paths.get(imagePath);
            byte[] imageBytes = Files.readAllBytes(path);
            String base64String = Base64.getEncoder().encodeToString(imageBytes);
            return new ImageUrl(base64String);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
     
`
Any help with resolving this issue would be greatly appreciated.

**Comment by sashirestela** [comment]
@safouat Glad to help you with this issue. I was able to replicate it locally and after that I did research in the OpenAI documentation. What I found is that you need to add a standard prefix to your base64 string, based on your image type:

```
private static ImageUrl loadImageAsBase64(String imagePath) {
    try {
        Path path = Paths.get(imagePath);
        byte[] imageBytes = Files.readAllBytes(path);
        String base64String = Base64.getEncoder().encodeToString(imageBytes);
        var extension = imagePath.substring(imagePath.lastIndexOf(".") + 1);
        var stdPrefix = "data:image/" + extension + ";base64,";
        return new ImageUrl(stdPrefix + base64String);
    } catch (Exception e) {
        e.printStackTrace();
        return null;
    }
}
```

Reference: https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images

Please, let me know if this works for you.

Sashir

**Comment by safouat** [comment]
Thank you, Mr. @sashirestela! It now works.
![Screenshot from 2024-01-20 19-48-18](https://github.com/sashirestela/simple-openai/assets/120058233/dd218894-3d4b-4785-926c-1798e5ed9e0b)

**Comment by sashirestela** [comment]
Closing without any code fixing
