### ISSUE TITLE
Support multiple OpenAI providers directly

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#45]
simple-openai was originally designed to interact with OpenAI only. Recent changes to cleverclient and simple-openai allow simple-openai to interact with multiple providers. The current known supported providers are:

- OpenAI
- Anyscale
- Azure OpenAI

The main high-level class - SimpleOpenAI has some implementation details that are not compatible with all providers such as authorization and organization id headers.

Proposal:
- Refactor the core functionality of SimpleOpenAI into a base class BaseSimpleOpenAI
- The SimpleOpenAI class will continue to support OpenAI and will remain backwards-compatible but will now extend BaseSimpleOpenAI. The job of SimpleOpenAI will only be to prepare the OpenAI specific headers and pass them to the constructor of the base class
- Additional providers like Azure OpenAI will extend the base class as well and provide their own modifications.

**Comment by sashirestela** [comment]
First, just to clarify, recent changes in **cleverclient** allow you to intercept the http request to modify it just to handle exceptional scenarios, so they are not allowing to interact with multiple providers _per se_.

For example, some providers could be using domain objects with a different structure than the standard one, so we cannot say that with those changes **simple-openai** is supporting multiple providers. More research is necessary here, especially with Azure OpenAI.

Is it a good idea to extend simple-openai to support multiple providers? It could be, if we are sure that those providers are fully compatible with the domain objects for requests and responses, which requires more testing.

A fully compatible provider, such as Anyscale seems to be, doesn't require any special treatment, it could work with the current implementation.

So, I think that you need to do research with the Azure OpenAI services and show evidence before to modify simple-openai. I'm afraid that you could find some differences that won't be easy to overcome. For example, as far I know, Azure is not supporting all the OpenAI services, but my main concern is with different responses.

**Comment by the-gigi** [comment]
this is all correct. the changes I have in mind are based on what is already known. The SimpleOpenAI class at the moment hard-codes some assumptions that are valid to OpenAI (and Anyscale), but not to OpenAzureAI. Specifically, the auth header and organization. If we want to take simple-openai in the direction of multi-provider support (still based on the OpenAI API) then it makes it cleaner and more elegant to move all the common parts into its own base class. Starting with the OpenAI assumptions and then removing them for other providers is non-symmetric.

I tested Azure OpenAI personally just with simple chat completion, but based on what I've read and seen the incompatibilities are all at the base url, query params and auth header. I plan to test chat completion with function calling. I don't have the bandwdith/resources to test it against other endpoints (remember each one requires a separate Azure OpenAI deployment). I think it's OK to add the Azure OpenAI wrapper and document clearly how it was tested. The existing functionality of supporting OpenAI, Anyscsle and Azure OpenAI with a single library with a user friendly access is very valuable already.

**Comment by sashirestela** [comment]
@the-gigi 

We could modify simple-openai to support multiple providers, partially, I mean, we should enable just the services that you have fully tested in every provider. For example, in the first iteration, the `SimpleAzureOpenAI` and the `SimpleAnyscaleOpenAI` should support the `chatCompletions()` service if it was fully tested for them. On next iterations you could deliver more services accordingly. This partial support must be communicated clearly to avoid wrong expectations. SimpleOpenAI will keep full support always.

With this approach in mind, the  abstract class `BaseSimpleOpenAI` will require the common fields: baseUrl, httpClient and cleverClient and the abstract declaration of all the eleven current services, so the specialized classes will have additional fields and will implement a subset of the services, throwing exceptions for the unimplemented services.

Let me know your thoughts.

**Comment by the-gigi** [comment]
Yep. Sounds good.

**Comment by sashirestela** [comment]
Ok, could you implement the change?

**Comment by the-gigi** [comment]
Yes. On it.

**Comment by the-gigi** [comment]
Let's discuss some more now that we have a concrete implementation to reference. Some points to consider:

Are the classes SimpleOpenAIAzure and SimpleOpenAIAnyscale useful? They provide a similar experience for the existing SimpleOpenAI, but they don't really do anything except prepare parameters to pass to the base class. SimpleOpenAI itself is exactly the same. Everything was pushed down to the base class.

Note that in the current state of the PR unsupported methods for Azure and Anyscale are not throwing yet. This could be a reason to keep the classes, so they can override methods and throw if not supported.

But, there is a problem with Azure. The model is baked into the deployment represented by the base URL. So, some more information will need to be provided at construction time for Azure as to what methods are supported.

In this case, we may replace the classes with a factory with static methods: `createOpenAI()`, `createAzureOpenAI()`, `createAnyscaleAI()` that will accept also a list of unsupported methods. Then, the base class can also check in each method call if it's one of unsupported methods and then throw.

**Comment by sashirestela** [comment]
@the-gigi

`BaseSimpleOpenAI` should be an interface that just declares the methods (the eleven services), not to implement them. We should implement the methods on the concrete classes, where `SimpleOpenAI` implements all the services, but `SimpleOpenAIAzure` and `SimpleOpenAIAnyscale` implements only a small subset and the rest throws exceptions of unimplemented type. Even more, every concrete class should have its own constructor with just their required parameters (ie: SimpleOpenAI does not require a requestInterceptor) and its own construction logic, including to create its own CleverClient object.

I'm not sure if the factory that you propose could be a valid option, I mean, passing methods as parameters could be a little brittle.

Let's try to keep it as simple as possible.

NOTE: I could not review your PR, because there are too many modified files (95), please, discard refactoring imports or things like that, let's focus on the main goal, please.

**Comment by the-gigi** [comment]
OK. I'll look into it today. Note that there is already an interface with all the services the OpenAI interface. SimpleOpenAI in practice implemented it, but not officially. It is defined as:

```
public class SimpleOpenAI {
```
and not

```
public class SimpleOpenAI implements OpenAI {
```

So, I'll restore SimpleOpenAI as it was (and add implements OpenAI to make it explicit and allow later to treat all OpenAI implementations to be used via the interface if needed, e.g. if some application want to work with multiple providers it will have multiple instances of OpenAI interface).

I'll do the other updates as you requested.
