### ISSUE TITLE
ThreadRun object is missing `usage` and `temperature`

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#68]
The [ThreadRun](https://github.com/sashirestela/simple-openai/blob/main/src/main/java/io/github/sashirestela/openai/domain/assistant/ThreadRun.java) object corresponds to the OpenAI API [run](https://platform.openai.com/docs/api-reference/runs/object) object

The OpenAI API run object has two fields: `usage` and `temperature` that are missing from the simple-openai ThreadRun object.

**Comment by sashirestela** [comment]
@the-gigi Thanks for identifying these missing fields. Checking the history in the OpenAI API spec, I can see that they were added after the first release of the Assistants API on Simple-OpenAI. Looks like there are more new fields.

As I was telling you some days ago, we need a mechanism to detect the differences automatically and that will be the next  functionality for Simple-OpenAI.
