### ISSUE TITLE
Add assistants API support for Azure OpenAI

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#73]
Azure OpenAI recently added support for the assistants API. Let's implement in in simple-openai

The URL and request structure of assistants API calls (As well as Files and Threads) is different from the existing /chat/completions and will requires changes to the HTTP request interceptor.

**Comment by sashirestela** [comment]
@the-gigi I suggest you sync your branch because several changes have been deployed on the weekend.

**Comment by the-gigi** [comment]
> @the-gigi I suggest you sync your branch because several changes have been added on the weekend.

done. the PR https://github.com/sashirestela/simple-openai/pull/72 is now ready for final review.
