### ISSUE TITLE
How to get OpenAIUsage when using Streams?

### ISSUE THREAD

**Issue by ndepomereu** [sashirestela/simple-openai#91]
Hi,
When using blocking call, it's easy to get tokens consumed:
```
    CompletableFuture<ChatResponse>  futureChat = openai.chatCompletions().create(chatRequest);
    ChatResponse chatResponse = futureChat.join();
    OpenAIUsage openAIUsage = chatResponse.getUsage();
    System.out.println(openAIUsage.getTotalTokens()); // Got it!
```
I just can't figure how to get OpenAIUsage or any other mean to count tokens when using Streams?
```
    var futureChat = openai.chatCompletions().createStream(chatRequest);
    var chatResponse = futureChat.join();
    chatResponse.filter(chatResp -> chatResp.firstContent() != null)
        .map(ChatResponse::firstContent)
        .forEach(System.out::print);
   System.out.println();
```
Any hint please? 

Best,
Nicolas

**Comment by sashirestela** [comment]
@ndepomereu I would invite you to use the [Discussion](https://github.com/sashirestela/simple-openai/discussions) section on this project, that is the most appropriate place to ask questions or suggestions.

Anyway, the short answer to your question is that OpenAI does not provide counting tokens for streaming, you could count on your side.

The [same question](https://community.openai.com/t/when-we-use-streaming-with-open-ai-models-i-am-not-getting-the-token-count/328008) has been asked several times in the OpenAI Forum and people suggest to count deltas and use a library to get tokens. In Java you could use the [JTokkit](https://github.com/knuddelsgmbh/jtokkit) library for the tokens part.

**Comment by ndepomereu** [comment]
@sashirestela thanks for your complete and detailed answer! 
I will follow the guidelines. 
My mistake; it was the first time ever I tried ChatGPT chunking, I could not imagine OpenAI bypassed this implementation.
Best,
N.
